### ISSUE TITLE
latexmk vs scripts

### ISSUE THREAD

**Issue by alexpovel** [thomasWeise/docker-texlive#3]
You use [custom scripts](https://github.com/thomasWeise/docker-texlive/tree/master/image/scripts) to emulate the entire compilation chain, including runs of auxiliary commands like `bibtex` (which could/should be replaced by `biblatex`/`biber`).

Have you stumbled over [`latexmk`](https://mg.readthedocs.io/latexmk.html) by any chance? It does precisely what you seem to be doing manually, but in a very mature and elaborate fashion. It is the de-facto standard for automated compilation chains (I only know of [`arara`](https://ctan.org/pkg/arara?lang=en) otherwise) and I have been using it with great success in Docker CI setups. It is customizable through `latexmkrc` files.

**Comment by thomasWeise** [comment]
Very nice.
Thanks for these infos - I indeed did not know about these tools.

I built my scripts quite some time ago, also as an attempt to learn how to write scripts in bash/linux.
I am using them ever since and don't have a direct personal reason to migrate to another tool right now.
Should I arrive at a point where the scripts I already have don't work, then I will definitely migrate, though.

Thank you ^_^.
Thomas.

**Comment by alexpovel** [comment]
> I built my scripts quite some time ago, also as an attempt to learn how to write scripts in bash/linux.
I am using them ever since and don't have a direct personal reason to migrate to another tool right now.

Yes, that makes sense!

Always happy to help... I will leave you with an example `.latexmkrc` file which can be placed next to whatever `*.tex` file is being compiled, among other places:

<https://gist.github.com/alexpovel/053433b58c17719f6ce2ee7535a0b052>

Cheers!
